// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace swp391_debo_be.Models;

public partial class Appointment
{
    public Guid Id { get; set; }

    public int? TreatId { get; set; }

    public Guid? TempDent { get; set; }

    public Guid? BookId { get; set; }

    public int? CusRecId { get; set; }

    public int? EstDuration { get; set; }

    public DateOnly? Date { get; set; }

    public string Description { get; set; }

    public virtual Booking Book { get; set; }

    public virtual CustomerRecord CusRec { get; set; }

    public virtual User TempDentNavigation { get; set; }

    public virtual ClinicTreatment Treat { get; set; }
}