// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace swp391_debo_be.Models;

public partial class ClinicTreatment
{
    public int Id { get; set; }

    public int? Category { get; set; }

    public Guid? AdminId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public double? Price { get; set; }

    public virtual User Admin { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual TreatmentCategory CategoryNavigation { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<Employee> Dents { get; set; } = new List<Employee>();
}