// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace swp391_debo_be.Models;

public partial class Manager
{
    public Guid Id { get; set; }

    public int? BrId { get; set; }

    public virtual ClinicBranch Br { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}